version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: fire_incidents_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fireuser
      POSTGRES_PASSWORD: firepass
      POSTGRES_DB: firedb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: