WITH current_data AS (
    SELECT * FROM {{ ref('fire_incidents_silver') }}
),
previous_data AS (
    SELECT * FROM {{ ref('fire_incidents_snapshot') }}
    WHERE dbt_valid_to IS NULL
)
SELECT
    CAST(COALESCE(c.id, p.id) AS TEXT) AS id,
    CAST(COALESCE(c.incident_number, p.incident_number) AS TEXT) AS incident_number,
    CAST(COALESCE(c.exposure_number, p.exposure_number) AS INTEGER) AS exposure_number,
    CAST(COALESCE(c.address, p.address) AS TEXT) AS address,
    CAST(COALESCE(c.incident_date, p.incident_date) AS TIMESTAMP) AS incident_date,
    CAST(COALESCE(c.call_number, p.call_number) AS TEXT) AS call_number,
    CAST(COALESCE(c.alarm_dttm, p.alarm_dttm) AS TIMESTAMP) AS alarm_dttm,
    CAST(COALESCE(c.arrival_dttm, p.arrival_dttm) AS TIMESTAMP) AS arrival_dttm,
    CAST(COALESCE(c.close_dttm, p.close_dttm) AS TIMESTAMP) AS close_dttm,
    CAST(COALESCE(c.city, p.city) AS TEXT) AS city,
    CAST(COALESCE(c.zipcode, p.zipcode) AS TEXT) AS zipcode,
    CAST(COALESCE(c.battalion, p.battalion) AS TEXT) AS battalion,
    CAST(COALESCE(c.station_area, p.station_area) AS TEXT) AS station_area,
    CAST(COALESCE(c.box, p.box) AS TEXT) AS box,
    CAST(COALESCE(c.suppression_units, p.suppression_units) AS INTEGER) AS suppression_units,
    CAST(COALESCE(c.suppression_personnel, p.suppression_personnel) AS INTEGER) AS suppression_personnel,
    CAST(COALESCE(c.ems_units, p.ems_units) AS INTEGER) AS ems_units,
    CAST(COALESCE(c.ems_personnel, p.ems_personnel) AS INTEGER) AS ems_personnel,
    CAST(COALESCE(c.other_units, p.other_units) AS INTEGER) AS other_units,
    CAST(COALESCE(c.other_personnel, p.other_personnel) AS INTEGER) AS other_personnel,
    CAST(COALESCE(c.first_unit_on_scene, p.first_unit_on_scene) AS TEXT) AS first_unit_on_scene,
    CAST(COALESCE(c.estimated_property_loss, p.estimated_property_loss) AS INTEGER) AS estimated_property_loss,
    CAST(COALESCE(c.estimated_contents_loss, p.estimated_contents_loss) AS INTEGER) AS estimated_contents_loss,
    CAST(COALESCE(c.fire_fatalities, p.fire_fatalities) AS INTEGER) AS fire_fatalities,
    CAST(COALESCE(c.fire_injuries, p.fire_injuries) AS INTEGER) AS fire_injuries,
    CAST(COALESCE(c.civilian_fatalities, p.civilian_fatalities) AS INTEGER) AS civilian_fatalities,
    CAST(COALESCE(c.civilian_injuries, p.civilian_injuries) AS INTEGER) AS civilian_injuries,
    CAST(COALESCE(c.number_of_alarms, p.number_of_alarms) AS INTEGER) AS number_of_alarms,
    CAST(COALESCE(c.primary_situation, p.primary_situation) AS TEXT) AS primary_situation,
    CAST(COALESCE(c.mutual_aid, p.mutual_aid) AS TEXT) AS mutual_aid,
    CAST(COALESCE(c.action_taken_primary, p.action_taken_primary) AS TEXT) AS action_taken_primary,
    CAST(COALESCE(c.action_taken_secondary, p.action_taken_secondary) AS TEXT) AS action_taken_secondary,
    CAST(COALESCE(c.action_taken_other, p.action_taken_other) AS TEXT) AS action_taken_other,
    CAST(COALESCE(c.detector_alerted_occupants, p.detector_alerted_occupants) AS TEXT) AS detector_alerted_occupants,
    CAST(COALESCE(c.property_use, p.property_use) AS TEXT) AS property_use,
    CAST(COALESCE(c.area_of_fire_origin, p.area_of_fire_origin) AS TEXT) AS area_of_fire_origin,
    CAST(COALESCE(c.ignition_cause, p.ignition_cause) AS TEXT) AS ignition_cause,
    CAST(COALESCE(c.ignition_factor_primary, p.ignition_factor_primary) AS TEXT) AS ignition_factor_primary,
    CAST(COALESCE(c.ignition_factor_secondary, p.ignition_factor_secondary) AS TEXT) AS ignition_factor_secondary,
    CAST(COALESCE(c.heat_source, p.heat_source) AS TEXT) AS heat_source,
    CAST(COALESCE(c.item_first_ignited, p.item_first_ignited) AS TEXT) AS item_first_ignited,
    CAST(COALESCE(c.human_factors_associated_with_ignition, p.human_factors_associated_with_ignition) AS TEXT) AS human_factors_associated_with_ignition,
    CAST(COALESCE(c.structure_type, p.structure_type) AS TEXT) AS structure_type,
    CAST(COALESCE(c.structure_status, p.structure_status) AS TEXT) AS structure_status,
    CAST(COALESCE(c.floor_of_fire_origin, p.floor_of_fire_origin) AS INTEGER) AS floor_of_fire_origin,
    CAST(COALESCE(c.fire_spread, p.fire_spread) AS TEXT) AS fire_spread,
    CAST(COALESCE(c.no_flame_spread, p.no_flame_spread) AS TEXT) AS no_flame_spread,
    CAST(COALESCE(c.number_of_floors_with_minimum_damage, p.number_of_floors_with_minimum_damage) AS INTEGER) AS number_of_floors_with_minimum_damage,
    CAST(COALESCE(c.number_of_floors_with_significant_damage, p.number_of_floors_with_significant_damage) AS INTEGER) AS number_of_floors_with_significant_damage,
    CAST(COALESCE(c.number_of_floors_with_heavy_damage, p.number_of_floors_with_heavy_damage) AS INTEGER) AS number_of_floors_with_heavy_damage,
    CAST(COALESCE(c.number_of_floors_with_extreme_damage, p.number_of_floors_with_extreme_damage) AS INTEGER) AS number_of_floors_with_extreme_damage,
    CAST(COALESCE(c.detectors_present, p.detectors_present) AS TEXT) AS detectors_present,
    CAST(COALESCE(c.detector_type, p.detector_type) AS TEXT) AS detector_type,
    CAST(COALESCE(c.detector_operation, p.detector_operation) AS TEXT) AS detector_operation,
    CAST(COALESCE(c.detector_effectiveness, p.detector_effectiveness) AS TEXT) AS detector_effectiveness,
    CAST(COALESCE(c.detector_failure_reason, p.detector_failure_reason) AS TEXT) AS detector_failure_reason,
    CAST(COALESCE(c.automatic_extinguishing_system_present, p.automatic_extinguishing_system_present) AS TEXT) AS automatic_extinguishing_system_present,
    CAST(COALESCE(c.automatic_extinguishing_sytem_type, p.automatic_extinguishing_sytem_type) AS TEXT) AS automatic_extinguishing_sytem_type,
    CAST(COALESCE(c.automatic_extinguishing_sytem_perfomance, p.automatic_extinguishing_sytem_perfomance) AS TEXT) AS automatic_extinguishing_sytem_perfomance,
    CAST(COALESCE(c.automatic_extinguishing_sytem_failure_reason, p.automatic_extinguishing_sytem_failure_reason) AS TEXT) AS automatic_extinguishing_sytem_failure_reason,
    CAST(COALESCE(c.number_of_sprinkler_heads_operating, p.number_of_sprinkler_heads_operating) AS INTEGER) AS number_of_sprinkler_heads_operating,
    CAST(COALESCE(c.supervisor_district, p.supervisor_district) AS TEXT) AS supervisor_district,
    CAST(COALESCE(c.neighborhood_district, p.neighborhood_district) AS TEXT) AS neighborhood_district,
    CAST(COALESCE(c.latitude, p.latitude) AS DOUBLE PRECISION) AS latitude,
    CAST(COALESCE(c.longitude, p.longitude) AS DOUBLE PRECISION) AS longitude,
    CAST(COALESCE(c.data_as_of, p.data_as_of) AS TIMESTAMP) AS data_as_of,
    CAST(COALESCE(c.data_loaded_at, p.data_loaded_at) AS DATE) AS data_loaded_at,
    CASE WHEN c.id IS NULL THEN FALSE ELSE TRUE END AS is_active,
    CURRENT_TIMESTAMP AS updated_at,
    CASE WHEN c.id IS NULL THEN CURRENT_TIMESTAMP ELSE NULL END AS deactivated_at
FROM previous_data p
FULL OUTER JOIN current_data c ON p.id = c.id
